const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const ts=require('typescript');
const cache=new Map();
// Load the pure TypeScript business logic without contacting a live database.
function load(file){const full=path.resolve(__dirname,'..',file);if(cache.has(full))return cache.get(full);const output=ts.transpileModule(fs.readFileSync(full,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{}};cache.set(full,module.exports);new Function('require','module','exports',output)(id=>{if(id==='./firebase-admin')return {};return id.startsWith('.')?load(path.relative(path.resolve(__dirname,'..'),path.resolve(path.dirname(full),id+'.ts'))):require(id);},module,module.exports);cache.set(full,module.exports);return module.exports;}
const {applyAction,hashPin,verifyPin,clockStatus}=load('lib/firebase-clock.ts');
const {validateBackup,backupPayload}=load('lib/firebase-store.ts');
const {centralMidnight,payPeriod}=load('lib/payroll.ts');
const {STORE_LOCATION}=load('lib/geofence.ts');
const now=Date.parse('2026-10-04T15:00:00Z');
function state(){return {storeId:'main',name:'Webb Chapel store',managerUid:'owner',managerEmail:'',location:STORE_LOCATION,geofenceEnabled:true,hash:hashPin('123456'),kioskEmail:'store@example.com',kioskUid:'kiosk',revision:0,generation:'initial',employees:[{id:'e1',name:'Employee',hash:hashPin('654321')}],shifts:[],payRates:[],audit:[]};}
test('PIN hashing stays compatible with original PBKDF2 hashes',()=>{const h=hashPin('654321','legacy-salt');assert.equal(h,'legacy-salt:'+require('node:crypto').pbkdf2Sync('654321','legacy-salt',100000,32,'sha256').toString('hex'));assert.equal(verifyPin('654321',h),true);assert.equal(verifyPin('111111',h),false);assert.equal(verifyPin({},h),false);});
test('clock-in requires fresh accurate store location; duplicate punch is rejected',()=>{const s=state();assert.throws(()=>applyAction(s,{action:'in',employee:'e1'},now),/Location/);const p={action:'in',employee:'e1',location:{latitude:STORE_LOCATION.latitude,longitude:STORE_LOCATION.longitude,accuracy:10,timestamp:now}};applyAction(s,p,now);assert.equal(s.shifts.length,1);assert.equal('location' in s.shifts[0],false);assert.throws(()=>applyAction(s,p,now),/Already clocked/);});
test('outside-store clock-in fails; clock-out requires no GPS',()=>{const s=state();assert.throws(()=>applyAction(s,{action:'in',employee:'e1',location:{latitude:0,longitude:0,accuracy:5,timestamp:now}},now),/300 feet/);s.shifts.push({id:'s1',employee:'e1',start:now-3600000,end:null});applyAction(s,{action:'out',employee:'e1'},now);assert.equal(s.shifts[0].end,now);});
test('manager shift changes reject overlap and stale edits',()=>{const s=state();s.shifts.push({id:'s1',employee:'e1',start:now-7200000,end:now-3600000});assert.throws(()=>applyAction(s,{action:'save_shift',employee:'e1',start:now-5400000,end:now,reason:'test'},now),/overlaps/);assert.throws(()=>applyAction(s,{action:'save_shift',employee:'e1',shift:'s1',originalStart:1,originalEnd:2,start:now-7200000,end:now-3600000,reason:'test'},now),/changed/);});
test('manual edits record before and after in audit',()=>{const s=state();applyAction(s,{action:'save_shift',employee:'e1',start:now-3600000,end:now,reason:'Forgot punch'},now);assert.equal(s.audit.length,1);assert.equal(s.audit[0].reason,'Forgot punch');assert.equal(JSON.parse(s.audit[0].after).start,now-3600000);});
test('twice-monthly hourly pay clips exact hours at period boundaries',()=>{const s=state();const start=centralMidnight('2026-10-01');s.shifts=[{id:'s1',employee:'e1',start:start-3600000,end:start+5400000}];s.payRates=[{id:'r1',employee:'e1',effective:'2026-10-01',type:'hourly',cents:1500}];const report=applyAction(s,{action:'payroll',period:'2026-10-01'});assert.equal(report.rows[0].hours,1.5);assert.equal(report.totalCents,2250);});
test('salary is fixed per period and active shift time is excluded',()=>{const s=state();s.payRates=[{id:'r1',employee:'e1',effective:'2026-10-01',type:'salary',cents:150000}];s.shifts=[{id:'s1',employee:'e1',start:now,end:null}];const report=applyAction(s,{action:'payroll',period:'2026-10-01'});assert.equal(report.totalCents,150000);assert.equal(report.rows[0].hours,0);assert.equal(report.rows[0].active,1);});
test('Central Time pay periods remain correct across daylight saving',()=>{const p=payPeriod('2026-11-01');assert.equal(p.endDate,'2026-11-15');assert.equal((p.end-p.start)/3600000,361);});
test('clock status never exposes payroll or PIN hashes',()=>{const view=clockStatus(state(),true);assert.equal(view.kiosk,true);assert.equal('hash' in view.employees[0],false);assert.equal('payRates' in view,false);});
test('legacy backup import preserves IDs and one-way PIN hashes',()=>{const s=state(),payload=backupPayload(s);payload.owner='old-chatgpt-user';assert.equal(validateBackup(payload).employees[0].id,'e1');assert.equal(validateBackup(payload).hash,s.hash);});
test('backup import rejects duplicate IDs, broken references and overlapping shifts',()=>{const p=backupPayload(state());p.tables.employees.push({...p.tables.employees[0]});assert.throws(()=>validateBackup(p),/duplicate/);p.tables.employees.pop();p.tables.shifts.push({id:'s1',employee:'missing',start:1,end:2});assert.throws(()=>validateBackup(p),/Invalid shift/);p.tables.shifts=[{id:'s1',employee:'e1',start:1,end:5},{id:'s2',employee:'e1',start:4,end:6}];assert.throws(()=>validateBackup(p),/overlapping/);});
test('geolocking off permits no-GPS punch; forged request flag cannot disable it',()=>{const s=state();assert.throws(()=>applyAction(s,{action:'in',employee:'e1',geofenceEnabled:false},now),/Location/);s.geofenceEnabled=false;applyAction(s,{action:'in',employee:'e1'},now);assert.equal(s.shifts.length,1);});
test('each store uses its own clock-in boundary',()=>{const s=state();s.location={...STORE_LOCATION,latitude:40,longitude:-80,address:'Other store'};assert.throws(()=>applyAction(s,{action:'in',employee:'e1',location:{latitude:STORE_LOCATION.latitude,longitude:STORE_LOCATION.longitude,accuracy:5,timestamp:now}},now),/Other store/);applyAction(s,{action:'in',employee:'e1',location:{latitude:40,longitude:-80,accuracy:5,timestamp:now}},now);assert.equal(s.shifts.length,1);});
test('geolocking changes are audited and reject invalid flag types',()=>{const s=state();applyAction(s,{action:'set_store',name:s.name,location:s.location,geofenceEnabled:false},now);assert.equal(s.geofenceEnabled,false);assert.equal(JSON.parse(s.audit[0].before).geofenceEnabled,true);assert.equal(JSON.parse(s.audit[0].after).geofenceEnabled,false);assert.throws(()=>applyAction(s,{action:'set_store',name:s.name,location:s.location,geofenceEnabled:'false'},now),/whether location/);});
test('tagged backups cannot be restored to another store; untagged legacy backups can import',()=>{const p=backupPayload(state());assert.throws(()=>validateBackup(p,'other'),/different store/);delete p.storeId;assert.equal(validateBackup(p,'other').employees.length,1);});
