const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const ts=require('typescript');
let database;
const accounts=new Map([['manager-a@example.com',{uid:'manager-a',emailVerified:true}],['manager-b@example.com',{uid:'manager-b',emailVerified:true}],['tablet-a@example.com',{uid:'tablet-a',emailVerified:true}]]);
// Route tests use already-verified identities and a transaction-capable memory
// database. No real Firebase tokens, keys, or live store records are used.
const admin={managerUid:()=> 'owner',firestore:()=>database,adminAuth:()=>({getUser:async uid=>{const account=[...accounts.values()].find(a=>a.uid===uid);if(!account)throw Error('Missing account');return account;},getUserByEmail:async email=>{if(!accounts.has(email))throw Error('Missing account');return accounts.get(email);}}),authenticatedUser:async req=>{const token=req.headers.get('Authorization');return token?.startsWith('Bearer ')?{uid:token.slice(7),email:token.slice(7)+'@example.com',email_verified:verifiedUsers.has(token.slice(7))}:null;}};
const verifiedUsers=new Set();
const codeQueue=[];
const cache=new Map();
function load(file){const full=path.resolve(__dirname,'..',file);if(cache.has(full))return cache.get(full);const output=ts.transpileModule(fs.readFileSync(full,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{}};cache.set(full,module.exports);new Function('require','module','exports',output)(id=>{if(id.endsWith('/firebase-admin')||id==='./firebase-admin')return admin;if(id==='node:crypto')return {...require(id),randomInt:(...args)=>codeQueue.length?codeQueue.shift():require(id).randomInt(...args)};return id.startsWith('.')?load(path.relative(path.resolve(__dirname,'..'),path.resolve(path.dirname(full),id+'.ts'))):require(id);},module,module.exports);cache.set(full,module.exports);return module.exports;}
function memory(initial){
 let rows=new Map(initial);const reads=[];
 const snap=(name)=>({id:name.split('/').pop(),exists:rows.has(name),data:()=>rows.has(name)?structuredClone(rows.get(name)):undefined});
 function query(name,filters=[],order=null,limit=null){return {name,filters,order,limitCount:limit,isQuery:true,doc:id=>ref(name+'/'+id),where:(key,op,value)=>{assert.equal(op,'==');return query(name,[...filters,[key,value]],order,limit);},orderBy:key=>query(name,filters,key,limit),limit:n=>query(name,filters,order,n),get:async()=>read(query(name,filters,order,limit))};}
 function ref(name){return {name,collection:key=>query(name+'/'+key),get:async()=>read(ref(name)),set:async(data,options)=>write(ref(name),data,options)};}
 function read(target){reads.push(target.name);if(!target.isQuery)return snap(target.name);let docs=[...rows.keys()].filter(k=>k.startsWith(target.name+'/')&&k.slice(target.name.length+1).indexOf('/')===-1).map(snap).filter(d=>target.filters.every(([key,value])=>d.data()[key]===value));if(target.order)docs.sort((a,b)=>String(target.order==='__name__'?a.id:a.data()[target.order]).localeCompare(String(target.order==='__name__'?b.id:b.data()[target.order])));if(target.limitCount)docs=docs.slice(0,target.limitCount);return {docs,size:docs.length,empty:docs.length===0};}
 function write(target,data,options){rows.set(target.name,{...(options?.merge?rows.get(target.name):{}),...structuredClone(data)});}
 return {recursiveDelete:async target=>{for(const key of [...rows.keys()])if(key===target.name||key.startsWith(target.name+'/'))rows.delete(key);},doc:ref,collection:query,getRows:()=>rows,getReads:()=>reads,runTransaction:async fn=>{const original=rows;rows=new Map(structuredClone([...rows]));try{return await fn({get:async target=>read(target),set:write,delete:target=>rows.delete(target.name)});}catch(e){rows=original;throw e;}},bulkWriter:()=>({set:async(target,data)=>write(target,data),close:async()=>{}})};
}
const clock=load('app/api/clock/route.ts');
const stores=load('app/api/stores/route.ts');
const {hashPin}=load('lib/firebase-clock.ts');
const {STORE_LOCATION}=load('lib/geofence.ts');
const {storeMeta,storeRole}=load('lib/store-policy.ts');
const managerHash=hashPin('123456'),employeeHash=hashPin('654321');
function fixture(){database=memory([
 ['storeAccessCodes/111111',{storeId:'a'}],['storeAccessCodes/222222',{storeId:'b'}],
 ['stores/a',{accessCode:'111111',name:'Store A',managerUid:'manager-a',managerEmail:'manager-a@example.com',kioskUid:'tablet-a',kioskEmail:'tablet-a@example.com',hash:managerHash,location:STORE_LOCATION,geofenceEnabled:true,revision:0,generation:'initial'}],
 ['stores/b',{accessCode:'222222',name:'Store B',managerUid:'manager-b',kioskUid:'tablet-b',kioskEmail:'tablet-b@example.com',hash:managerHash,location:{...STORE_LOCATION,latitude:40,longitude:-80},geofenceEnabled:true,revision:0,generation:'initial'}],
 ['stores/a/generations/initial/employees/same-id',{id:'same-id',name:'Alice A',hash:employeeHash}],
 ['stores/b/generations/initial/employees/same-id',{id:'same-id',name:'Bob B',hash:employeeHash}],
 ['stores/b/backups/other-backup',{complete:true,chunks:1}],
 ['stores/b/backups/other-backup/chunks/00000000',{text:JSON.stringify({secret:'store-b-payroll'})}]
]);}
function req(uid,storeId,body){const headers={Host:'localhost',Origin:'http://localhost','Content-Type':'application/json'};if(uid)headers.Authorization='Bearer '+uid;if(storeId)headers['X-Store-ID']=storeId;return new Request('http://localhost/api/clock',{method:body?'POST':'GET',headers,...(body?{body:JSON.stringify(body)}:{})});}
test('manager and kiosk store listings exclude other stores',async()=>{fixture();for(const uid of ['manager-a','tablet-a']){const r=await stores.GET(req(uid)),data=await r.json();assert.equal(r.status,200);assert.deepEqual(data.stores.map(s=>s.id),['a']);assert.equal(data.owner,false);}const owner=await (await stores.GET(req('owner'))).json();assert.deepEqual(new Set(owner.stores.map(s=>s.id)),new Set(['main','a','b']));});
test('manager cannot read another store even when forging its ID',async()=>{fixture();assert.equal((await clock.GET(req('manager-a','b'))).status,403);const data=await (await clock.GET(req('manager-a','a'))).json();assert.equal(data.employees[0].name,'Alice A');assert.equal('hash' in data.employees[0],false);});
test('tablet cannot read another store or run manager actions',async()=>{fixture();assert.equal((await clock.GET(req('tablet-a','b'))).status,403);for(const action of ['payroll','report','backup_download','set_store','set_kiosk','setup']){const response=await clock.POST(req('tablet-a','a',{action,pin:'123456',key:'other-backup',geofenceEnabled:false}));assert.equal(response.status,403,action);}});
test('unauthenticated, missing-store and path-traversal requests are rejected',async()=>{fixture();assert.equal((await clock.GET(req(null,'a'))).status,401);assert.equal((await clock.GET(req('manager-a'))).status,400);assert.equal((await clock.GET(req('manager-a','../b'))).status,400);});
test('manager cannot write another store or create stores',async()=>{fixture();const before=structuredClone([...database.getRows()]);assert.equal((await clock.POST(req('manager-a','b',{action:'add',pin:'123456',name:'Intruder',employeePin:'111111'}))).status,403);assert.equal((await stores.POST(req('manager-a',null,{action:'create',managerEmail:'manager-a@example.com'}))).status,403);assert.deepEqual([...database.getRows()],before);});
test('backup keys are scoped to their store',async()=>{fixture();const response=await clock.POST(req('manager-a','a',{action:'backup_download',pin:'123456',key:'other-backup'}));assert.notEqual(response.status,200);assert.equal((await response.text()).includes('store-b-payroll'),false);});
test('geolocking bypass flag is ignored; authorized switch affects only one store',async()=>{fixture();assert.equal((await clock.POST(req('tablet-a','a',{action:'in',employee:'same-id',pin:'654321',geofenceEnabled:false}))).status,403);const updated=await clock.POST(req('manager-a','a',{action:'set_store',pin:'123456',name:'Store A',location:STORE_LOCATION,geofenceEnabled:false}));assert.equal(updated.status,200);assert.equal(database.getRows().get('stores/b').geofenceEnabled,true);assert.equal((await clock.POST(req('tablet-a','a',{action:'in',employee:'same-id',pin:'654321'}))).status,200);assert.equal([...database.getRows().keys()].filter(k=>k.startsWith('stores/b/generations/initial/shifts/')).length,0);});
test('owner can reassign manager and old manager loses access',async()=>{fixture();assert.equal((await stores.POST(req('owner',null,{action:'assign_manager',storeId:'a',managerEmail:'manager-b@example.com'}))).status,200);assert.equal((await clock.GET(req('manager-a','a'))).status,403);assert.equal((await clock.GET(req('manager-b','a'))).status,200);});
test('owner can create new store; manager must finish PIN setup',async()=>{fixture();const response=await stores.POST(req('owner',null,{action:'create',managerEmail:'manager-a@example.com',name:'New business',location:STORE_LOCATION,geofenceEnabled:true}));assert.equal(response.status,200);const {id}=await response.json();const status=await (await clock.GET(req('manager-a',id))).json();assert.equal(status.setup,false);assert.deepEqual(status.employees,[]);assert.equal((await clock.GET(req('manager-b',id))).status,403);});
test('manager cannot reuse another store tablet or a manager account',async()=>{fixture();accounts.set('tablet-b@example.com',{uid:'tablet-b',emailVerified:true});for(const email of ['tablet-b@example.com','manager-b@example.com'])assert.equal((await clock.POST(req('manager-a','a',{action:'set_kiosk',pin:'123456',email}))).status,400);assert.equal(database.getRows().get('stores/a').kioskUid,'tablet-a');});
test('legacy main store remains accessible only to owner until assigned',()=>{const legacy=storeMeta('main',{},'owner');assert.equal(storeRole('owner',legacy,'owner'),'manager');assert.equal(storeRole('manager-a',legacy,'owner'),null);assert.equal(legacy.geofenceEnabled,true);});
const personal=load('app/api/employee/route.ts');
function linkFixture(){fixture();database.getRows().set('storeAccounts/alice',{role:'employee',stores:{a:'same-id',b:'same-id'}});for(const id of ['a','b'])database.getRows().set(`stores/${id}/employeeAccess/same-id`,{uid:'alice',email:'alice@example.com'});accounts.set('alice@example.com',{uid:'alice',emailVerified:true});}
test('employee sees only own assigned stores, shifts and pay without PIN hashes',async()=>{linkFixture();database.getRows().set('stores/a/generations/initial/employees/secret',{id:'secret',name:'Other',hash:employeeHash});database.getRows().set('stores/a/generations/initial/payRates/secret-rate',{id:'secret-rate',employee:'secret',effective:'2026-10-01',type:'salary',cents:999999});const list=await (await stores.GET(req('alice'))).json();assert.deepEqual(list.stores.map(s=>s.role),['employee','employee']);const r=await personal.GET(new Request('http://localhost/api/employee?period=2026-10-01',{headers:{Authorization:'Bearer alice'}}));assert.equal(r.status,200);const d=await r.json();assert.equal(d.stores.length,2);assert.equal(JSON.stringify(d).includes('999999'),false);assert.equal(JSON.stringify(d).includes(employeeHash),false);});
test('employee cannot use manager actions, select another employee or bypass location',async()=>{linkFixture();assert.equal((await clock.POST(req('alice','a',{action:'report',pin:'123456'}))).status,403);assert.equal((await clock.POST(req('alice','a',{action:'in',employee:'other'}))).status,403);assert.equal((await clock.POST(req('alice','a',{action:'in',geofenceEnabled:false}))).status,403);assert.equal((await personal.POST(req('alice','a',{action:'list',pin:'123456'}))).status,403);});
test('linked employee punch requires no PIN and blocks overlap across stores including tablet punches',async()=>{linkFixture();for(const id of ['a','b'])database.getRows().get('stores/'+id).geofenceEnabled=false;assert.equal((await clock.POST(req('alice','a',{action:'in'}))).status,200);assert.equal((await clock.POST(req('alice','b',{action:'in'}))).status,409);assert.equal((await clock.POST(req('tablet-b','b',{action:'in',employee:'same-id',pin:'654321'}))).status,409);assert.equal((await clock.POST(req('alice','a',{action:'out'}))).status,200);assert.equal((await clock.POST(req('alice','b',{action:'in'}))).status,200);});
test('managers link an employee email per store and cannot link manager identities',async()=>{fixture();accounts.set('alice@example.com',{uid:'alice',emailVerified:true});const body={action:'link',employee:'same-id',email:'alice@example.com',pin:'123456'};assert.equal((await personal.POST(req('manager-a','b',body))).status,403);assert.equal((await personal.POST(req('manager-a','a',body))).status,200);assert.equal((await personal.POST(req('manager-b','b',body))).status,200);assert.deepEqual(database.getRows().get('storeAccounts/alice').stores,{a:'same-id',b:'same-id'});assert.equal((await stores.POST(req('owner',null,{action:'assign_manager',storeId:'a',managerEmail:'alice@example.com'}))).status,400);assert.equal((await clock.POST(req('manager-a','a',{action:'set_kiosk',email:'alice@example.com',pin:'123456'}))).status,400);assert.equal((await personal.POST(req('manager-a','a',{...body,email:'manager-b@example.com'}))).status,400);});
test('unlink revokes only one store and prevents employee reads/punches there',async()=>{linkFixture();assert.equal((await personal.POST(req('manager-a','a',{action:'unlink',employee:'same-id',pin:'123456'}))).status,200);assert.equal((await clock.POST(req('alice','a',{action:'in'}))).status,403);const r=await personal.GET(new Request('http://localhost/api/employee?period=2026-10-01',{headers:{Authorization:'Bearer alice'}}));assert.deepEqual((await r.json()).stores.map(s=>s.id),['b']);});

test('employee email clock-out enforces store geolocking on server',async()=>{linkFixture();const now=Date.now();database.getRows().set('stores/a/generations/initial/shifts/open',{id:'open',employee:'same-id',start:now-3600000,end:null});for(const location of [undefined,{latitude:0,longitude:0,accuracy:5,timestamp:now}]){assert.equal((await clock.POST(req('alice','a',{action:'out',location,geofenceEnabled:false}))).status,403);assert.equal(database.getRows().get('stores/a/generations/initial/shifts/open').end,null);}assert.equal((await clock.POST(req('alice','a',{action:'out',location:{latitude:STORE_LOCATION.latitude,longitude:STORE_LOCATION.longitude,accuracy:5,timestamp:Date.now()}}))).status,200);});

test('backup delete requires manager login, stays store scoped, and removes chunks only',async()=>{fixture();const rows=database.getRows();rows.set('stores/a/backups/remove-me',{complete:true,chunks:1});rows.set('stores/a/backups/remove-me/chunks/00000000',{text:'copy'});assert.equal((await clock.POST(req('tablet-a','a',{action:'backup_delete',pin:'123456',key:'remove-me'}))).status,403);assert.equal((await clock.POST(req(null,'a',{action:'backup_delete',key:'remove-me'}))).status,401);assert.equal(rows.has('stores/a/backups/remove-me'),true);assert.equal((await clock.POST(req('manager-a','b',{action:'backup_delete',pin:'123456',key:'other-backup'}))).status,403);assert.equal((await clock.POST(req('manager-a','a',{action:'backup_delete',pin:'123456',key:'remove-me'}))).status,200);const current=database.getRows();assert.equal(current.has('stores/a/backups/remove-me'),false);assert.equal(current.has('stores/a/backups/remove-me/chunks/00000000'),false);assert.equal(current.has('stores/a/generations/initial/employees/same-id'),true);assert.equal(current.has('stores/b/backups/other-backup'),true);});
test('saved edits no longer create backups; manual backups still work',async()=>{fixture();assert.equal((await clock.POST(req('manager-a','a',{action:'add',pin:'123456',name:'New employee'}))).status,200);assert.equal([...database.getRows().keys()].some(k=>k.startsWith('stores/a/backups/')),false);assert.equal((await clock.POST(req('manager-a','a',{action:'backup_create',pin:'123456'}))).status,200);assert.equal([...database.getRows().keys()].some(k=>k.startsWith('stores/a/backups/')),true);});
const {runDailyBackups,dayEnded}=require('../functions/daily-backups.js');
test('daily schedule labels Central dates across daylight saving and deduplicates retries',async()=>{assert.equal(dayEnded('2026-10-06T05:00:00Z'),'2026-10-05');assert.equal(dayEnded('2026-11-02T06:00:00Z'),'2026-11-01');fixture();await runDailyBackups(database,'2026-10-06T05:00:00Z');const key='stores/a/backups/daily-2026-10-05';assert.equal(database.getRows().get(key).kind,'daily');const first=structuredClone([...database.getRows()]);await runDailyBackups(database,'2026-10-06T05:00:00Z');assert.deepEqual([...database.getRows()],first);const payload=JSON.parse(database.getRows().get(key+'/chunks/00000000').text);assert.equal(payload.tables.employees[0].name,'Alice A');assert.equal(payload.storeId,'a');assert.equal(database.getRows().get('stores/b/backups/daily-2026-10-05').complete,true);});

test('failed daily chunk writes remain incomplete and a retry recovers',async()=>{fixture();const original=database.bulkWriter;database.bulkWriter=()=>({set:async()=>{throw Error('simulated write failure');},close:async()=>{}});await assert.rejects(runDailyBackups(database,'2026-10-06T05:00:00Z'));assert.equal(database.getRows().has('stores/a/backups/daily-2026-10-05'),false);database.bulkWriter=original;await runDailyBackups(database,'2026-10-06T05:00:00Z');assert.equal(database.getRows().get('stores/a/backups/daily-2026-10-05').complete,true);});
test('employee email account cannot delete backups',async()=>{linkFixture();assert.equal((await clock.POST(req('alice','a',{action:'backup_delete',pin:'123456',key:'anything'}))).status,403);});
test('archive revokes only selected store access and preserves records',async()=>{linkFixture();const rows=database.getRows();rows.set('stores/a/generations/initial/shifts/past',{id:'past',employee:'same-id',start:1,end:2});assert.equal((await personal.POST(req('tablet-a','a',{action:'archive',pin:'123456',employee:'same-id'}))).status,403);assert.equal((await personal.POST(req(null,'a',{action:'archive',employee:'same-id'}))).status,401);assert.equal((await personal.POST(req('manager-a','a',{action:'archive',pin:'123456',employee:'same-id'}))).status,200);const current=database.getRows();assert.ok(current.get('stores/a/generations/initial/employees/same-id').archivedAt);assert.equal(current.get('stores/a/generations/initial/employees/same-id').hash,null);assert.ok(current.has('stores/a/generations/initial/shifts/past'));assert.equal((await clock.POST(req('alice','a',{action:'in'}))).status,403);const access=await (await stores.GET(req('alice'))).json();assert.deepEqual(access.stores.map(s=>s.id),['b']);const status=await (await clock.GET(req('manager-a','a'))).json();assert.equal(status.employees.length,0);assert.equal(status.archivedEmployees.length,1);});
test('archive refuses open shifts and wrong-store managers',async()=>{linkFixture();database.getRows().set('stores/a/generations/initial/shifts/open',{employee:'same-id',start:1,end:null});assert.equal((await personal.POST(req('manager-b','a',{action:'archive',pin:'123456',employee:'same-id'}))).status,403);assert.equal((await personal.POST(req('manager-a','a',{action:'archive',pin:'123456',employee:'same-id'}))).status,400);assert.equal(database.getRows().get('stores/a/generations/initial/employees/same-id').archivedAt,undefined);});

const requests=load('app/api/access-requests/route.ts');
function requestFixture(){fixture();verifiedUsers.clear();verifiedUsers.add('newbie');accounts.set('newbie@example.com',{uid:'newbie',email:'newbie@example.com',emailVerified:true});}
test('unverified requests denied; pending login has no clock or payroll access',async()=>{requestFixture();const body={action:'submit',name:'New Person',accessCode:'111111'};assert.equal((await requests.POST(req('unverified',null,body))).status,403);assert.equal((await requests.POST(req('newbie',null,body))).status,200);assert.equal((await requests.POST(req('newbie',null,body))).status,200);assert.equal(database.getRows().get('stores/a/accessRequests/newbie').status,'pending');assert.equal((await clock.GET(req('newbie','a'))).status,403);assert.equal((await personal.GET(req('newbie'))).status,403);assert.deepEqual((await (await stores.GET(req('newbie'))).json()).stores,[]);assert.equal((await (await requests.GET(req('newbie'))).json()).requests.length,1);assert.equal((await (await requests.GET(req('unverified'))).json()).requests.length,0);});
test('scoped manager approval links history once; wrong manager, signed-out user and tablet rejected',async()=>{requestFixture();await requests.POST(req('newbie',null,{action:'submit',name:'New Person',accessCode:'111111'}));const body={action:'approve',uid:'newbie',employee:'same-id',pin:'123456'};assert.equal((await requests.POST(req('manager-b','a',body))).status,403);assert.equal((await requests.POST(req('tablet-a','a',body))).status,403);assert.equal((await requests.POST(req(null,'a',body))).status,401);assert.equal((await requests.POST(req('manager-a','a',body))).status,200);assert.equal(database.getRows().get('storeAccounts/newbie').stores.a,'same-id');assert.equal(database.getRows().get('stores/a/generations/initial/employees/same-id').name,'Alice A');assert.equal(database.getRows().get('accessRequests/newbie/stores/a').status,'approved');assert.equal((await requests.POST(req('manager-a','a',body))).status,409);assert.equal((await personal.GET(new Request('http://localhost/api/employee?period=2026-10-01',{headers:{Authorization:'Bearer newbie'}}))).status,200);});
test('new employee approval supports second store; rejection grants no access',async()=>{requestFixture();for(const id of ['a','b'])await requests.POST(req('newbie',null,{action:'submit',name:'New Person',accessCode:id==='a'?'111111':'222222'}));assert.equal((await requests.POST(req('manager-a','a',{action:'approve',uid:'newbie',pin:'123456'}))).status,200);assert.equal((await requests.POST(req('manager-b','b',{action:'approve',uid:'newbie',pin:'123456'}))).status,200);const entries=database.getRows().get('storeAccounts/newbie').stores;assert.deepEqual(Object.keys(entries),['a','b']);assert.notEqual(entries.a,entries.b);assert.equal(database.getRows().get('stores/a/generations/initial/employees/'+entries.a).hash,null);requestFixture();await requests.POST(req('newbie',null,{action:'submit',name:'New Person',accessCode:'111111'}));assert.equal((await requests.POST(req('manager-a','a',{action:'reject',uid:'newbie',pin:'123456'}))).status,200);assert.equal(database.getRows().has('storeAccounts/newbie'),false);assert.equal((await requests.POST(req('newbie',null,{action:'submit',name:'New Person',accessCode:'111111'}))).status,429);});
test('approval rejects linked, archived, active records and changed email',async()=>{for(const condition of ['linked','archived','active','email']){requestFixture();await requests.POST(req('newbie',null,{action:'submit',name:'New Person',accessCode:'111111'}));const rows=database.getRows();if(condition==='linked')rows.set('stores/a/employeeAccess/same-id',{uid:'someone',email:'someone@example.com'});if(condition==='archived')rows.get('stores/a/generations/initial/employees/same-id').archivedAt=Date.now();if(condition==='active')rows.set('stores/a/generations/initial/shifts/open',{employee:'same-id',start:1,end:null});if(condition==='email')accounts.get('newbie@example.com').email='changed@example.com';assert.equal((await requests.POST(req('manager-a','a',{action:'approve',uid:'newbie',employee:'same-id',pin:'123456'}))).status,400,condition);assert.equal(database.getRows().has('storeAccounts/newbie'),false);assert.equal(database.getRows().get('stores/a/accessRequests/newbie').status,'pending');}});

const {ensureStoreAccessCode,validAccessCode}=load('lib/store-access-code.ts');
test('store codes are six digits, stable, unique, and migrate existing stores',async()=>{fixture();database.getRows().set('storeAccessCodes/333333',{storeId:'occupied'});codeQueue.push(333333,444444);const code=await ensureStoreAccessCode('main');assert.equal(code,'444444');assert.equal(await ensureStoreAccessCode('main'),code);assert.equal(database.getRows().get('storeAccessCodes/333333').storeId,'occupied');assert.equal(database.getRows().get('storeAccessCodes/444444').storeId,'main');const listing=await (await stores.GET(req('manager-a'))).json();assert.equal(listing.stores[0].accessCode,'111111');assert.equal(validAccessCode('main'),false);assert.equal(validAccessCode('123456'),true);});
test('employee requests resolve numeric codes to stores and reject raw store IDs',async()=>{requestFixture();for(const accessCode of ['a','main','000000','11111'])assert.equal((await requests.POST(req('newbie',null,{action:'submit',name:'New Person',accessCode}))).status,400);assert.equal((await requests.POST(req('newbie',null,{action:'submit',name:'New Person',accessCode:'222222'}))).status,200);assert.equal(database.getRows().get('stores/b/accessRequests/newbie').storeId,'b');assert.equal(database.getRows().has('stores/a/accessRequests/newbie'),false);});
test('manager email session opens management APIs without PIN despite stale lockout',async()=>{fixture();database.getRows().set('stores/a/attempts/manager',{count:99,until:Date.now()+999999});for(const action of ['report','payroll','backup_list','get_store']){const response=await clock.POST(req('manager-a','a',{action,period:'2026-10-01'}));assert.equal(response.status,200,action);}assert.equal((await personal.POST(req('manager-a','a',{action:'list'}))).status,200);assert.equal((await requests.POST(req('manager-a','a',{action:'list'}))).status,200);assert.equal((await clock.POST(req('manager-a','a',{action:'add',name:'Email managed employee'}))).status,403);assert.equal((await clock.POST(req('manager-a','a',{action:'add',name:'Email managed employee',pin:'123456'}))).status,429);assert.equal((await requests.POST(req('tablet-a','a',{action:'list'}))).status,403);assert.equal((await personal.POST(req('manager-b','a',{action:'list'}))).status,403);});
test('kiosk employee PIN is still enforced when manager PIN gate is removed',async()=>{fixture();database.getRows().get('stores/a').geofenceEnabled=false;assert.equal((await clock.POST(req('tablet-a','a',{action:'in',employee:'same-id'}))).status,403);assert.equal((await clock.POST(req('tablet-a','a',{action:'in',employee:'same-id',pin:'000000'}))).status,403);assert.equal((await clock.POST(req('tablet-a','a',{action:'in',employee:'same-id',pin:'654321'}))).status,200);});

test('reports open without PIN but administrative and destructive changes retain PIN checks',async()=>{fixture();for(const action of ['backup_delete','backup_restore','backup_download','add','save_shift'])assert.equal((await clock.POST(req('manager-a','a',{action,key:'anything',employee:'same-id',name:'New employee'}))).status,403,action);assert.equal((await personal.POST(req('manager-a','a',{action:'archive',employee:'same-id'}))).status,403);assert.equal((await requests.POST(req('manager-a','a',{action:'reject',uid:'anything'}))).status,403);assert.equal((await clock.POST(req('manager-a','a',{action:'backup_create',pin:'123456'}))).status,200);});

const noBusinessReads=()=>assert.deepEqual(database.getReads().filter(p=>p.includes('/generations/')),[]);
test('unassigned and wrong-store POSTs reject before reading business collections',async()=>{
 for(const uid of ['stranger','manager-b'])for(const [route,body] of [[clock,{action:'report'}],[personal,{action:'link',email:'missing@example.com'}],[requests,{action:'approve',uid:'missing'}]]){
  fixture();const before=structuredClone([...database.getRows()]);const response=await route.POST(req(uid,'a',body));assert.equal(response.status,403);noBusinessReads();assert.deepEqual([...database.getRows()],before);
 }
});
test('unauthorized clock and employee routes never consume the body',async()=>{
 for(const route of [clock,personal]){fixture();const request=req('stranger','a',{action:'list'});const response=await route.POST(request);assert.equal(response.status,403);assert.equal(request.bodyUsed,false);noBusinessReads();}
});
test('employee and tablet forbidden actions reject before business reads',async()=>{
 for(const uid of ['alice','tablet-a']){linkFixture();const response=await clock.POST(req(uid,'a',{action:'backup_download',key:'x'}));assert.equal(response.status,403);assert.equal(database.getReads().some(p=>/\/generations\/[^/]+\/(shifts|payRates|audit)$/.test(p)),false);}
});
test('manager access is rechecked inside the write transaction before full state reads',async()=>{
 for(const [route,body] of [[clock,{action:'add',pin:'123456',name:'x'}],[personal,{action:'list'}],[requests,{action:'list'}]]){
  fixture();const transact=database.runTransaction;database.runTransaction=fn=>{database.getRows().get('stores/a').managerUid='replacement';return transact(fn);};
  assert.equal((await route.POST(req('manager-a','a',body))).status,403);noBusinessReads();
 }
});
test('access request submit uses metadata only, never employee/payroll history',async()=>{
 requestFixture();assert.equal((await requests.POST(req('newbie',null,{action:'submit',accessCode:'111111',name:'New employee'}))).status,200);noBusinessReads();
});
test('every email assignment rejects unverified accounts without mutations',async()=>{
 for(const verified of [false,undefined])for(const action of ['link','set_kiosk','assign_manager','create']){
  fixture();accounts.set('unverified@example.com',{uid:'unverified',email:'unverified@example.com',emailVerified:verified});const before=structuredClone([...database.getRows()]);
  const route=action==='link'?personal:action==='set_kiosk'?clock:stores;
  const body={action,email:'unverified@example.com',managerEmail:'unverified@example.com',storeId:'a',employee:'same-id',pin:'123456',name:'New store',location:STORE_LOCATION};
  const response=await route.POST(req(['create','assign_manager'].includes(action)?'owner':'manager-a','a',body));assert.equal(response.status,400);assert.match((await response.json()).error,/verify/i);assert.deepEqual([...database.getRows()],before);
 }
});
test('verified tablet assignment succeeds while disabled accounts remain rejected',async()=>{
 fixture();accounts.set('verified-tablet@example.com',{uid:'verified-tablet',emailVerified:true});assert.equal((await clock.POST(req('manager-a','a',{action:'set_kiosk',email:'verified-tablet@example.com',pin:'123456'}))).status,200);
 accounts.set('disabled@example.com',{uid:'disabled',emailVerified:true,disabled:true});for(const [route,action] of [[clock,'set_kiosk'],[personal,'link'],[stores,'assign_manager']])assert.equal((await route.POST(req(action==='assign_manager'?'owner':'manager-a','a',{action,email:'disabled@example.com',managerEmail:'disabled@example.com',storeId:'a',employee:'same-id',pin:'123456'}))).status,400);
});
test('oversized normal requests stop before state reads on all POST routes',async()=>{
 for(const [route,action] of [[clock,'report'],[personal,'list'],[requests,'list'],[stores,'assign_manager']]){fixture();const response=await route.POST(req(route===stores?'owner':'manager-a','a',{action,padding:'x'.repeat(11000)}));assert.equal(response.status,413);noBusinessReads();}
});
test('large upload gate is manager-only and cannot disguise a non-import action',async()=>{
 for(const uid of ['stranger','tablet-a','alice']){linkFixture();const original=req(uid,'a',{action:'backup_import',padding:'x'.repeat(11000)}),request=new Request('http://localhost/api/clock?action=backup_import',original);assert.equal((await clock.POST(request)).status,403);assert.equal(request.bodyUsed,false);}
 fixture();const original=req('manager-a','a',{action:'report',padding:'x'.repeat(11000)});assert.equal((await clock.POST(new Request('http://localhost/api/clock?action=backup_import',original))).status,400);noBusinessReads();
});
test('authorized valid import exceeds normal limit and preserves backup/PIN checks',async()=>{
 fixture();const {snapshot,backupPayload}=load('lib/firebase-store.ts');const payload=backupPayload(await snapshot('a'));
 payload.tables.audit=Array.from({length:30},(_,i)=>({id:'test-'+i,at:1,action:'save_shift',employee:'Alice A',reason:'x'.repeat(500),before:null,after:null}));assert.ok(JSON.stringify(payload).length>10000);
 const original=req('manager-a','a',{action:'backup_import',pin:'123456',payload});const response=await clock.POST(new Request('http://localhost/api/clock?action=backup_import',original));assert.equal(response.status,200);assert.equal((await snapshot('a')).audit.length,30);assert.equal((await snapshot('a')).employees[0].name,'Alice A');
 const denied=req('manager-a','a',{action:'backup_import',pin:'wrong',payload});assert.equal((await clock.POST(new Request('http://localhost/api/clock?action=backup_import',denied))).status,403);
});
const {boundedJson}=load('lib/request-body.ts');
test('bounded reader counts streamed bytes despite missing or false content length and cancels',async()=>{
 for(const length of [null,'1']){let cancelled=false,pulls=0;const stream=new ReadableStream({pull(c){pulls++;c.enqueue(new Uint8Array(4000));},cancel(){cancelled=true;}},{highWaterMark:0});const request=new Request('http://localhost',{method:'POST',body:stream,duplex:'half',headers:length?{'Content-Length':length}:{}});await assert.rejects(boundedJson(request),e=>e.status===413);assert.equal(cancelled,true);assert.equal(pulls,3);}
});
test('bounded reader rejects declared oversize before consumption and malformed JSON safely',async()=>{
 let pulls=0;const stream=new ReadableStream({pull(c){pulls++;c.close();}},{highWaterMark:0});await assert.rejects(boundedJson(new Request('http://localhost',{method:'POST',body:stream,duplex:'half',headers:{'Content-Length':'20000001'}}),20000000),e=>e.status===413);assert.equal(pulls,0);
 for(const body of ['null','[]','{'])await assert.rejects(boundedJson(new Request('http://localhost',{method:'POST',body})),e=>e.status===400);
});
