const test=require('node:test'),assert=require('node:assert/strict');
const {lastClosedPeriod,buildReport,reportPdf}=require('../functions/payroll-report');
const {recipientsFor,runPayrollEmails}=require('../functions/payroll-email');
function memory(initial){const rows=new Map(initial);let queue=Promise.resolve();const snap=path=>({id:path.split('/').pop(),exists:rows.has(path),data:()=>structuredClone(rows.get(path))});const read=r=>r.query?{docs:[...rows.keys()].filter(k=>k.startsWith(r.path+'/')&&!k.slice(r.path.length+1).includes('/')).map(snap)}:snap(r.path);const doc=path=>({path,get:async()=>read({path}),set:async(data,opts)=>rows.set(path,{...(opts?.merge?rows.get(path):{}),...structuredClone(data)}),collection:n=>collection(path+'/'+n)});const collection=path=>({path,query:true,doc:n=>doc(path+'/'+n),get:async()=>read({path,query:true})});return {rows,doc,collection,runTransaction:fn=>{const work=queue.then(()=>fn({get:async r=>read(r),set:(r,v)=>rows.set(r.path,structuredClone(v))}));queue=work.catch(()=>{});return work;}};}
function fixture(){const rows=[];for(const id of ['a','b']){rows.push(['stores/'+id,{hash:'configured',name:'Store '+id,managerUid:'manager-'+id,generation:'initial'}]);rows.push([`stores/${id}/generations/initial/employees/e`,{name:'Employee '+id}]);rows.push([`stores/${id}/generations/initial/shifts/s`,{employee:'e',start:Date.parse('2026-10-02T12:00:00Z'),end:Date.parse('2026-10-02T20:00:00Z')}]);rows.push([`stores/${id}/generations/initial/payRates/r`,{employee:'e',type:'hourly',cents:1500,effective:'2026-10-01'}]);}const db=memory(rows),users={owner:{uid:'owner',email:'owner@example.com'},'manager-a':{uid:'manager-a',email:'a@example.com'},'manager-b':{uid:'manager-b',email:'b@example.com'}};const auth={getUser:async uid=>{if(!users[uid])throw Object.assign(Error('missing'),{code:'auth/user-not-found'});return users[uid];}};const sent=[];return {db,auth,users,sent,ownerUid:'owner',scheduleTime:'2026-10-16T11:00:00Z',makePdf:async report=>Buffer.from(report.storeId),transport:{sendMail:async mail=>{sent.push(mail);return {accepted:[mail.to],messageId:'test'};}}};}
test('closed periods handle month/year boundaries, leap year and DST',()=>{assert.equal(lastClosedPeriod('2026-10-16T11:00:00Z').startDate,'2026-10-01');assert.equal(lastClosedPeriod('2026-11-01T12:00:00Z').endDate,'2026-10-31');assert.equal(lastClosedPeriod('2027-01-01T12:00:00Z').startDate,'2026-12-16');assert.equal(lastClosedPeriod('2024-03-01T12:00:00Z').endDate,'2024-02-29');const p=lastClosedPeriod('2026-03-16T11:00:00Z');assert.equal((p.end-p.start)/3600000,359);});
test('report matches app payroll including boundary clipping, salary, archive and open shifts',()=>{const p=lastClosedPeriod('2026-10-16T11:00:00Z'),state={storeId:'a',name:'Store',employees:[{id:'h',name:'Hourly'},{id:'s',name:'Salary'},{id:'n',name:'Missing'},{id:'old',name:'Archived',archivedAt:p.start-1}],shifts:[{id:'1',employee:'h',start:p.start-3600000,end:p.start+7200000},{id:'2',employee:'h',start:p.end-3600000,end:p.end+3600000},{id:'3',employee:'h',start:p.start+100,end:null}],payRates:[{employee:'h',type:'hourly',cents:1550,effective:p.startDate},{employee:'s',type:'salary',cents:150000,effective:p.startDate}]};const r=buildReport(state,p);assert.equal(r.totalHours,3);assert.equal(r.totalCents,154650);assert.equal(r.open,1);assert.equal(r.completed,2);assert.equal(r.unconfigured,1);assert.equal(r.rows.length,3);
 const fs=require('node:fs'),ts=require('../node_modules/typescript'),path=require('node:path'),cache=new Map();function load(file){const full=path.resolve(__dirname,'..',file);if(cache.has(full))return cache.get(full);const m={exports:{}};const code=ts.transpileModule(fs.readFileSync(full,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','module','exports',code)(id=>id.startsWith('.')?load(path.relative(path.resolve(__dirname,'..'),path.resolve(path.dirname(full),id+'.ts'))):require(id),m,m.exports);cache.set(full,m.exports);return m.exports;}
 const expected=load('lib/firebase-clock.ts').payroll(state,{period:p.startDate});assert.equal(r.totalCents,expected.totalCents);assert.deepEqual(r.rows.map(x=>[x.id,x.hours,x.payCents]),expected.rows.map(x=>[x.id,x.hours,x.payCents]));});
test('recipients are current manager UID plus owner, deduplicated and disabled managers excluded',async()=>{const f=fixture();assert.deepEqual((await recipientsFor(f.auth,{managerUid:'manager-a',managerEmail:'wrong@example.com'},'a','owner')).recipients.map(x=>x.email),['owner@example.com','a@example.com']);f.users['manager-a'].disabled=true;assert.equal((await recipientsFor(f.auth,{managerUid:'manager-a'},'a','owner')).recipients.length,1);assert.equal((await recipientsFor(f.auth,{managerUid:'owner'},'a','owner')).recipients.length,1);});
test('store reports stay isolated, owner gets all, retries use same snapshot and skip sent mail',async()=>{const f=fixture();await runPayrollEmails(f);assert.equal(f.sent.length,4);assert.equal(f.sent.filter(x=>x.to==='owner@example.com').length,2);assert.equal(f.sent.find(x=>x.to==='a@example.com').attachments[0].content.toString(),'a');assert.equal(f.sent.find(x=>x.to==='b@example.com').attachments[0].content.toString(),'b');f.db.rows.get('stores/a/generations/initial/payRates/r').cents=9999;await runPayrollEmails(f);assert.equal(f.sent.length,4);assert.equal(f.db.rows.get('stores/a/payrollReports/2026-10-01').report.totalCents,12000);});
test('uncertain delivery is flagged and not blindly resent while other stores continue',async()=>{const f=fixture();f.transport.sendMail=async mail=>{f.sent.push(mail);if(mail.to==='a@example.com')throw Error('connection lost after SMTP data');return {accepted:[mail.to]};};await assert.rejects(runPayrollEmails(f));assert.equal(f.sent.length,4);assert([...f.db.rows.values()].some(x=>x.status==='needs_review'));await assert.rejects(runPayrollEmails(f));assert.equal(f.sent.length,4);});
test('manager assignment is checked again immediately before sending',async()=>{const f=fixture();f.transport.sendMail=async mail=>{f.sent.push(mail);if(mail.to==='owner@example.com')f.db.rows.get('stores/a').managerUid='manager-b';return {accepted:[mail.to]};};await runPayrollEmails(f);assert(!f.sent.some(m=>m.to==='a@example.com'));});
test('PDF renders summary and paginated detailed shifts',async()=>{const f=fixture(),p=lastClosedPeriod(f.scheduleTime);const state={storeId:'demo',name:'Example Store',employees:[{id:'e',name:'Example Employee'}],payRates:[{employee:'e',type:'hourly',cents:1750,effective:p.startDate}],shifts:Array.from({length:65},(_,i)=>({id:String(i),employee:'e',start:p.start+i*3600000,end:p.start+(i+1)*3600000}))};const pdf=await reportPdf(buildReport(state,p));assert.equal(pdf.subarray(0,4).toString(),'%PDF');require('node:fs').writeFileSync('/tmp/timeclock-payroll-preview.pdf',pdf);});
