"use client";
import {useEffect,useState} from 'react';
import {useStoreApi} from './store-context';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function EmployeeAccess({pin}:{pin:string}){
 const api=useStoreApi(),[employees,setEmployees]=useState<{id:string;name:string;email:string}[]>([]),[selected,setSelected]=useState(''),[email,setEmail]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function request(body:any){const r=await api('/api/employee',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,pin})});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d;}
 async function load(){const d=await request({action:'list'});setEmployees(d.employees);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[api,pin]);
 async function save(action:string){setBusy(true);setError('');setMessage('');try{await request({action,employee:selected,email});await load();setMessage(action==='link'?'Employee email linked. Assign the same email at another store to enable both.':'Email access removed from this store.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="panel"><h2>Employee email access</h2><p>Create the employee’s email/password account in Firebase Authentication first. Link the same email to their employee record at each store where they work. Employees can see only their own hours and estimated gross pay.</p>{error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}<Button variant="outline" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh employee list</Button><form onSubmit={e=>{e.preventDefault();save('link');}}><label htmlFor="employee-email-person">Employee</label><select id="employee-email-person" required value={selected} onChange={e=>{setSelected(e.target.value);setEmail(employees.find(p=>p.id===e.target.value)?.email??'');}}><option value="">Choose employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}{e.email?' · '+e.email:''}</option>)}</select><label htmlFor="employee-email">Login email</label><Input id="employee-email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><Button disabled={busy||!selected} type="submit">Link email</Button><Button variant="outline" disabled={busy||!selected} type="button" onClick={()=>{if(window.confirm('Remove this employee’s email access from this store?'))save('unlink');}}>Remove email access</Button></form><p className="muted">Clock out before changing access. Existing PIN access and salary calculations stay in place.</p></section>;
}
