"use client";
import {useEffect,useState,useCallback} from 'react';
import {apiFetch} from '../lib/firebase-client';
import {currentLocation,locationError} from '../lib/geofence';
import type {StoreLocation} from '../lib/geofence';
import {Button} from '@/components/ui/button';
function initialPeriod(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${Number(p.day)<16?'01':'16'}`;}
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
const fmt=(n:number)=>new Date(n).toLocaleString('en-US',{timeZone:'America/Chicago'});
type PersonalStore={id:string;name:string;employee:string;nameEmployee:string;location:StoreLocation|null;geofenceEnabled:boolean;start:number|null;pay:{hours:number;payCents:number|null;type:string|null};shifts:{id:string;start:number;end:number|null}[]};
export default function EmployeeDashboard({storeId}:{storeId:string}){
 const [period,setPeriod]=useState(initialPeriod),[stores,setStores]=useState<PersonalStore[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const r=await apiFetch('/api/employee?period='+encodeURIComponent(period));const d:any=await r.json();if(!r.ok)throw Error(d.error);setStores(d.stores);},[period]);
 useEffect(()=>{let active=true;setStores([]);load().catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[load]);
 const store=stores.find(s=>s.id===storeId),activeElsewhere=stores.some(s=>s.id!==storeId&&s.start!==null);
 async function punch(action:string){if(!store)return;setBusy(true);setError('');setMessage('');try{let location;if(['in','out'].includes(action)&&store.geofenceEnabled){setMessage('Checking location…');location=await currentLocation();const problem=locationError(location,Date.now(),store.location);if(problem)throw Error(problem);}const r=await apiFetch('/api/clock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,location})},store.id);const d:any=await r.json();if(!r.ok)throw Error(d.error);await load();setMessage(action==='in'?'You are clocked in.':'You are clocked out.');}catch(e:any){setMessage('');setError(e.message);}finally{setBusy(false);}}
 return <main><h1>My time clock</h1>{error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}<section className="panel"><h2>{store?.name??'Loading…'}</h2><p>{store?.nameEmployee}</p><p>{store?.start?`Clocked in since ${fmt(store.start)}`:'Currently clocked out'}</p><p>{store?.geofenceEnabled?'Precise location is required at clock-in and clock-out.':'Geolocking is off for this store.'}</p><div className="punch-buttons"><Button disabled={busy||!store||store.start!==null||activeElsewhere} onClick={()=>punch('in')}>Clock in</Button><Button variant="outline" disabled={busy||!store||store.start===null} onClick={()=>punch('out')}>Clock out</Button></div>{activeElsewhere&&<p>Clock out at your other store before clocking in here.</p>}<Button variant="outline" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh</Button></section><section className="panel"><h2>My hours and estimated pay</h2><label htmlFor="personal-period">Pay period starts on the 1st or 16th</label><input id="personal-period" type="date" value={period} onChange={e=>{setError('');setPeriod(e.target.value);}}/><p>Completed hours: <b>{stores.reduce((n,s)=>n+s.pay.hours,0).toFixed(2)}</b> · Estimated gross pay: <b>{money(stores.reduce((n,s)=>n+(s.pay.payCents??0),0))}</b>{stores.some(s=>s.pay.payCents===null)&&' (some stores have no pay rate configured)'}</p><p className="muted">Before taxes and deductions. Active shifts count after clock-out. Salary remains the existing per-store amount for the pay period.</p>{stores.map(s=><div className="employee-row" key={s.id}><b>{s.name}</b><span>{s.pay.hours.toFixed(2)} hours · {s.pay.payCents===null?'Pay rate not set':money(s.pay.payCents)}</span></div>)}</section><section className="panel"><h2>My shift history · {store?.name}</h2><p>All times in Central Time.</p>{store?.shifts.map(s=><div className="employee-row" key={s.id}><span>{fmt(s.start)} → {s.end?fmt(s.end):'On the clock'}</span><b>{s.end?((s.end-s.start)/3600000).toFixed(2)+' hours':'In progress'}</b></div>)}{store&&!store.shifts.length&&<p>No shifts yet.</p>}</section></main>;
}
