"use client";
import {useState} from 'react';
import {useStoreApi} from './store-context';
import {Button} from '@/components/ui/button';
export default function ImportBackup({pin}:{pin?:string}){
 const apiFetch=useStoreApi();
 const [payload,setPayload]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <section className="panel"><h2>Import an existing backup</h2><p>Choose a downloaded Store Time Clock JSON backup to transfer employees, PINs, shifts, pay settings, and change history. Firebase account access stays unchanged.</p>{error&&<p className="notice error" role="alert">{error}</p>}<label htmlFor="backup-file">Backup file</label><input id="backup-file" type="file" accept=".json,application/json" disabled={busy} onChange={async e=>{setError('');setPayload(null);try{const f=e.target.files?.[0];if(!f)return;if(f.size>20000000)throw Error('Maximum backup size is 20 MB.');const data=JSON.parse(await f.text());if(data.format!=='store-time-clock-backup'||data.version!==1)throw Error('Choose a Store Time Clock JSON backup.');setPayload(data);}catch(e:any){setError(e.message);}}}/>{payload&&<p>{payload.tables?.employees?.length??0} employees · {payload.tables?.shifts?.length??0} shifts · backup dated {payload.createdAt}</p>}<Button disabled={!payload||busy} onClick={async()=>{if(!window.confirm('Import this backup? Current employees, shifts, pay settings, manager PIN, and change history will be replaced. A safety backup is saved first.'))return;setBusy(true);setError('');try{const r=await apiFetch('/api/clock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'backup_import',pin,payload})});const d:any=await r.json();if(!r.ok)throw Error(d.error);window.location.reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{busy?'Importing…':'Import backup'}</Button></section>;
}
