'use client';
import {apiFetch} from '../lib/firebase-client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
type Shift={id:string;employee:string;start:number;end:number|null;name:string};
const local=(v:number)=>{const d=new Date(v);return new Date(v-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const fmt=(v:number)=>new Date(v).toLocaleString('en-US',{timeZone:'America/Chicago'});
export default function ManagerTools({employees,shifts,pin,onSaved,logs}:{employees:{id:string;name:string}[];shifts:Shift[];pin:string;onSaved:()=>Promise<void>;logs:any[]}){
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<Shift|null>(null),[mode,setMode]=useState('shift'),[employee,setEmployee]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[name,setName]=useState(''),[newPin,setNewPin]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false);
 const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 function begin(s:Shift|null=null,kind='shift',id=''){setEditing(s);setMode(kind);setEmployee(s?.employee||id);setStart(local(s?.start||Date.now()));setEnd(s?.end?local(s.end):'');setName(employees.find(e=>e.id===id)?.name||'');setNewPin('');setReason('');setError('');setOpen(true);}
 async function save(action:string){setBusy(true);setError('');try{if(!reason.trim())throw Error('Enter a reason for this change.');const startTime=editing&&start===local(editing.start)?editing.start:new Date(start).getTime();const endTime=end?(editing?.end&&end===local(editing.end)?editing.end:new Date(end).getTime()):null;
 const r=await apiFetch('/api/clock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,pin,employee,shift:editing?.id,originalStart:editing?.start,originalEnd:editing?.end,start:startTime,end:endTime,name,employeePin:newPin,reason})});const d:any=await r.json();if(!r.ok)throw Error(d.error);await onSaved();setOpen(false);setConfirm(false);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="panel manager-tools"><div className="section-title"><div><h2>Manual controls</h2><p>Manager changes can be made from any location.</p></div><Button disabled={!employees.length} onClick={()=>begin()}>Add / clock in manually</Button></div><div className="manual-list">{employees.map(e=><div key={e.id}><b>{e.name}</b><Button variant="outline" onClick={()=>begin(null,'employee',e.id)}>Edit name / PIN</Button><Button variant="outline" onClick={()=>begin(null,'shift',e.id)}>Add shift</Button></div>)}</div><h3>Correct a shift</h3><p className="muted">Edit either time, end an active shift, or delete a mistaken entry.</p><div className="manual-list">{shifts.map(s=><div key={s.id}><span><b>{s.name}</b><small>{fmt(s.start)} — {s.end?fmt(s.end):'On the clock'} · Central</small></span><Button variant="outline" onClick={()=>begin(s)}>{s.end?'Edit shift':'Edit / clock out'}</Button></div>)}{!shifts.length&&<p className="muted">No shifts to edit yet.</p>}</div><h3>Recent manager changes</h3><div className="audit-list">{logs.map((l,i)=><div key={i}><b>{l.employee} · {l.action==='save_shift'?'Shift saved':l.action==='delete_shift'?'Shift deleted':l.action==='set_pay'?'Pay setting updated':l.action==='set_kiosk'?'Tablet access updated':'Employee updated'}</b><small>{fmt(l.at)} Central</small><p>{l.reason}</p>{!['edit_employee','set_kiosk'].includes(l.action)&&<small>{l.before&&<>Before: {describe(l.before)}<br/></>}{l.after&&<>After: {describe(l.after)}</>}</small>}</div>)}{!logs.length&&<p className="muted">Manual changes will appear here.</p>}</div>
 <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v);}}><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>{mode==='employee'?'Edit employee':editing?'Correct shift':'Add a manual shift'}</DialogTitle><DialogDescription>{mode==='employee'?'Leave the new PIN blank to keep the current PIN.':`Enter times in ${timezone} (this device’s timezone). Leave clock-out blank for an active shift.`}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();save(mode==='employee'?'edit_employee':'save_shift');}}>{error&&<p role="alert" className="notice error">{error}</p>}{mode==='employee'?<><label htmlFor="edit-name">Employee name</label><Input id="edit-name" value={name} maxLength={80} required onChange={e=>setName(e.target.value)}/><label htmlFor="edit-pin">New PIN (optional · 6–12 digits)</label><Input id="edit-pin" type="password" inputMode="numeric" value={newPin} minLength={6} maxLength={12} onChange={e=>setNewPin(e.target.value)}/></>:<><label>Employee</label><Select value={employee} onValueChange={setEmployee} disabled={!!editing}><SelectTrigger className="w-full"><SelectValue placeholder="Choose an employee"/></SelectTrigger><SelectContent>{employees.map(e=><SelectItem key={e.id} value={e.id}>{e.name}</SelectItem>)}</SelectContent></Select><label htmlFor="manual-start">Clock in</label><Input id="manual-start" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} required/><Button type="button" variant="outline" onClick={()=>setStart(local(Date.now()))}>Set clock-in to now</Button><label htmlFor="manual-end">Clock out (blank = still working)</label><Input id="manual-end" type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/><Button type="button" variant="outline" onClick={()=>setEnd(local(Date.now()))}>Set clock-out to now</Button></>}<label htmlFor="reason">Reason for change</label><Input id="reason" value={reason} maxLength={500} required placeholder="e.g. Forgot to clock out" onChange={e=>setReason(e.target.value)}/><div className="form-actions"><Button type="submit" disabled={busy||!employee}>{busy?'Saving…':'Save changes'}</Button>{editing&&<Button type="button" variant="destructive" disabled={busy||!reason.trim()} onClick={()=>setConfirm(true)}>Delete shift</Button>}</div></form></DialogContent></Dialog>
 <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this shift?</AlertDialogTitle><AlertDialogDescription>This removes the shift from hour totals. The reason and original times remain in the manager change history.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>save('delete_shift')}>Delete shift</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>;
}
function describe(value:string){try{const s=JSON.parse(value);if(s.type)return `${s.type==='salary'?'Salary per pay period':'Hourly'}: $${(s.cents/100).toFixed(2)} · effective ${s.effective}`;return `${fmt(s.start)} — ${s.end?fmt(s.end):'On the clock'}`;}catch{return 'Details unavailable';}}
