'use client';
import {apiFetch} from '../lib/firebase-client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Row={id:string;name:string;type:'hourly'|'salary'|null;cents:number|null;effective:string|null;hours:number;payCents:number|null;active:number};
type Report={period:{startDate:string;endDate:string};rows:Row[];totalCents:number;unconfigured:number};
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
function today(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const d=Object.fromEntries(parts.map(p=>[p.type,p.value]));return {month:`${d.year}-${d.month}`,half:Number(d.day)<=15?'01':'16'};}
export default function Payroll({pin,revision,onSaved}:{pin:string;revision:unknown;onSaved:()=>Promise<void>}){
const [initial]=useState(today),[month,setMonth]=useState(initial.month),[half,setHalf]=useState(initial.half),[report,setReport]=useState<Report|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState<Row|null>(null),[type,setType]=useState('hourly'),[rate,setRate]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[formError,setFormError]=useState('');
const period=`${month}-${half}`;
async function call(body:any,signal?:AbortSignal){const r=await apiFetch('/api/clock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,pin}),signal});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d;}
useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setReport(null);call({action:'payroll',period},controller.signal).then(d=>setReport(d)).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[period,pin,revision]);
function edit(row:Row){setEditing(row);setType(row.type||'hourly');setRate(row.cents===null?'':(row.cents/100).toFixed(2));setReason('');setFormError('');}
async function save(){setBusy(true);setFormError('');try{await call({action:'set_pay',employee:editing?.id,period,type,rate,reason});setReport(await call({action:'payroll',period}));await onSaved();setEditing(null);}catch(e:any){setFormError(e.message);}finally{setBusy(false);}}
return <section className="panel payroll"><div className="section-title"><div><p className="eyebrow">TWICE-MONTHLY PAY</p><h2>Hours & pay owed</h2><p>1st–15th and 16th–last day · Central Time</p></div><div className="pay-selectors"><div><label htmlFor="pay-month">Month</label><Input id="pay-month" type="month" min="2000-01" max="2100-12" value={month} onChange={e=>setMonth(e.target.value)}/></div><div><label>Pay period</label><Select value={half} onValueChange={setHalf}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="01">1st–15th</SelectItem><SelectItem value="16">16th–last day</SelectItem></SelectContent></Select></div></div></div>{loading&&<p role="status">Calculating pay…</p>}{error&&<p className="notice error" role="alert">{error}</p>}{report&&<><div className="pay-summary"><div><span>Base gross pay owed</span><strong>{money(report.totalCents)}</strong></div><div><span>Total completed hours</span><strong>{report.rows.reduce((n,r)=>n+r.hours,0).toFixed(2)} hrs</strong></div><p>{report.period.startDate} through {report.period.endDate}</p></div>{report.unconfigured>0&&<p className="notice">Set pay for {report.unconfigured} employee{report.unconfigured===1?'':'s'} to complete this total. Unset pay is excluded.</p>}<Table><TableHeader><TableRow><TableHead>Employee</TableHead><TableHead>Pay type</TableHead><TableHead>Rate</TableHead><TableHead>Hours</TableHead><TableHead>Gross pay</TableHead><TableHead>Settings</TableHead></TableRow></TableHeader><TableBody>{report.rows.map(row=><TableRow key={row.id}><TableCell><b>{row.name}</b>{row.active>0&&<small className="pay-active">Active shift excluded</small>}</TableCell><TableCell>{row.type==='salary'?'Salary':row.type==='hourly'?'Hourly':'Not set'}</TableCell><TableCell>{row.cents===null?'—':`${money(row.cents)} / ${row.type==='salary'?'pay period':'hour'}`}</TableCell><TableCell>{row.hours.toFixed(2)}</TableCell><TableCell><b>{row.payCents===null?'Not set':money(row.payCents)}</b></TableCell><TableCell><Button variant="outline" onClick={()=>edit(row)}>{row.type?'Edit pay':'Set pay'}</Button></TableCell></TableRow>)}</TableBody></Table>{!report.rows.length&&<p className="empty">Add employees below to set their pay.</p>}<p className="muted pay-explanation">Hourly pay = completed hours × hourly rate. Salary = the full fixed amount for this pay period, regardless of hours. Active shifts are excluded from hours until clock-out. No taxes, deductions, overtime premiums, salary proration, or paid/unpaid tracking are applied. Pay is rounded to cents after calculation using exact recorded time.</p></>}
<Dialog open={!!editing} onOpenChange={v=>{if(!v&&!busy)setEditing(null);}}><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>Pay settings · {editing?.name}</DialogTitle><DialogDescription>Effective from {period}. Applies to this period and later periods until another rate takes effect. Earlier periods keep their existing rate.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();save();}}>{formError&&<p role="alert" className="notice error">{formError}</p>}<label>Pay type</label><Select value={type} onValueChange={setType}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="hourly">Hourly</SelectItem><SelectItem value="salary">Salary · per pay period</SelectItem></SelectContent></Select><label htmlFor="pay-rate">{type==='salary'?'Salary per half-month pay period ($)':'Hourly rate ($)'}</label><Input id="pay-rate" type="number" inputMode="decimal" step="0.01" min="0" max="9999999.99" required value={rate} onChange={e=>setRate(e.target.value)}/>{type==='salary'&&<p className="muted">Enter one pay period’s salary. For a $3,000 monthly salary, enter $1,500.</p>}<label htmlFor="pay-reason">Reason</label><Input id="pay-reason" required maxLength={500} value={reason} placeholder="e.g. Initial pay setup or rate increase" onChange={e=>setReason(e.target.value)}/><Button disabled={busy} type="submit">{busy?'Saving…':'Save pay settings'}</Button></form></DialogContent></Dialog></section>;
}
