"use client";
import {useState} from 'react';
import {apiFetch} from '../lib/firebase-client';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {LocationFields,emptyDraft,settingsBody} from './store-settings';
export type StoreChoice={id:string;name:string;role:'manager'|'kiosk';managerEmail?:string;managerUid?:string};
export default function StoreAdmin({stores,onSaved}:{stores:StoreChoice[];onSaved:()=>Promise<void>}){
 const [draft,setDraft]=useState(emptyDraft),[email,setEmail]=useState(''),[target,setTarget]=useState(''),[replacement,setReplacement]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function save(body:any){setBusy(true);setError('');setMessage('');try{const r=await apiFetch('/api/stores',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error);await onSaved();setMessage(body.action==='create'?'Store created. Its assigned manager can now sign in and set up employees.':'Manager assignment updated. The previous manager loses access unless assigned to this store again.');if(body.action==='create'){setDraft(emptyDraft);setEmail('');}}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <main><section className="panel"><h1>Business and store access</h1><p>Your owner account creates stores and assigns managers. Each manager sees only stores assigned to their Firebase account. Your owner account retains access to all stores.</p><p>Create each manager’s separate email/password account in Firebase Authentication first. Give each store a separate tablet account too.</p>{error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}<h2>Add a store</h2><form onSubmit={e=>{e.preventDefault();save({action:'create',managerEmail:email,...settingsBody(draft)});}}><LocationFields draft={draft} onChange={setDraft} prefix="new-store"/><label htmlFor="store-manager">Assigned manager’s Firebase email</label><Input id="store-manager" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><Button type="submit" disabled={busy}>{busy?'Saving…':'Create store'}</Button></form><h2>Current manager assignments</h2><div className="manual-list">{stores.map(s=><div key={s.id}><span><b>{s.name}</b><small>{s.managerEmail||s.managerUid}</small></span></div>)}</div><h2>Change a store’s manager</h2><form onSubmit={e=>{e.preventDefault();if(window.confirm('Replace this store’s manager? The previous manager will lose access to this store. The owner keeps access.'))save({action:'assign_manager',storeId:target,managerEmail:replacement});}}><label htmlFor="manager-store">Store</label><select id="manager-store" required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose a store</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><label htmlFor="replacement-manager">New manager’s Firebase email</label><Input id="replacement-manager" type="email" required value={replacement} onChange={e=>setReplacement(e.target.value)}/><Button disabled={busy||!target} type="submit">Assign manager</Button></form><p className="muted">A replacement manager will need this store’s manager PIN. Accounts are managed in Firebase Authentication; this screen does not create passwords or delete employee data.</p></section></main>;
}
