"use client";
import {useEffect,useState} from 'react';
import type {StoreLocation} from '../lib/geofence';
import {useStoreApi} from './store-context';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export type StoreDraft={name:string;address:string;latitude:string;longitude:string;feet:string;geofenceEnabled:boolean};
export const emptyDraft:StoreDraft={name:'',address:'',latitude:'',longitude:'',feet:'300',geofenceEnabled:true};
export function settingsBody(d:StoreDraft){return {name:d.name,geofenceEnabled:d.geofenceEnabled,location:{address:d.address,latitude:Number(d.latitude),longitude:Number(d.longitude),radiusMeters:Number(d.feet)*0.3048}};}
export function LocationFields({draft,onChange,prefix}:{draft:StoreDraft;onChange:(d:StoreDraft)=>void;prefix:string}){
 const field=(key:Exclude<keyof StoreDraft,'geofenceEnabled'>,label:string,type='text',step?:string)=><div key={key}><label htmlFor={prefix+'-'+key}>{label}</label><Input id={prefix+'-'+key} value={draft[key]} type={type} step={step} maxLength={key==='name'?100:300} required onChange={e=>onChange({...draft,[key]:e.target.value})}/></div>;
 return <>{field('name','Business / store name')}{field('address','Store address')}<label className="geo-switch" htmlFor={prefix+'-locking'}><input id={prefix+'-locking'} type="checkbox" role="switch" checked={draft.geofenceEnabled} onChange={e=>onChange({...draft,geofenceEnabled:e.target.checked})}/><span>Geolocking {draft.geofenceEnabled?'on':'off'}</span></label><p className="muted">{draft.geofenceEnabled?'Employees must be near this store to clock in.':'Employees can clock in from any location. PINs and store access remain required.'}</p><p className="muted">Enter the coordinates of the store entrance. In Google Maps, right-click the location to see its latitude and longitude. An address alone does not set the clock-in boundary.</p>{field('latitude','Latitude','number','any')}{field('longitude','Longitude','number','any')}{field('feet','Clock-in radius (feet; default 300)','number','any')}</>;
}
export default function StoreSettings({pin,onSaved}:{pin:string;onSaved:()=>Promise<void>}){
 const apiFetch=useStoreApi();
 const [draft,setDraft]=useState(emptyDraft),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;apiFetch('/api/clock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'get_store',pin})}).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error);if(active){const l:StoreLocation|null=d.location;setDraft({name:d.name,address:l?.address??'',latitude:l?String(l.latitude):'',longitude:l?String(l.longitude):'',feet:l?String(Math.round(l.radiusMeters/0.3048*100)/100):'300',geofenceEnabled:d.geofenceEnabled!==false});setReady(true);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[pin,apiFetch]);
 return <section className="panel"><h2>Store name and location</h2><p>These settings affect only this store. Clock-in radius must be between 66 and 3280 feet (20–1000 meters).</p>{error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}{ready&&<form onSubmit={async e=>{e.preventDefault();if(!window.confirm('Update this store’s name and clock-in location?'))return;setBusy(true);setError('');setMessage('');try{const r=await apiFetch('/api/clock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'set_store',pin,...settingsBody(draft)})});const d:any=await r.json();if(!r.ok)throw Error(d.error);await onSaved();setMessage('Store settings saved. Test clock-in on the store tablet.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><LocationFields draft={draft} onChange={setDraft} prefix="location"/><Button disabled={busy} type="submit">{busy?'Saving…':'Save store settings'}</Button></form>}</section>;
}
